### ISSUE TITLE
Add popup

### ISSUE THREAD

**Issue by azaky** [azaky/wikigame#4]
At the current stage, the only way to start a game is to include `?roomId=...` in the URL. This is a good way to join a game via link sharing, but it's not a really great experience when a user wants to start a new game.

A simple popup containing a minimal form (name & room) is needed. Something like this:

![D11c331969dacc71d571103255e1c6065](https://user-images.githubusercontent.com/5902356/95673472-f8caa580-0bd2-11eb-9633-abc5b9d4ff59.png)

To help getting started, here's the guide for creating Chrome extension popup: https://developer.chrome.com/extensions/user_interface#popup

**Comment by erlanggawulung** [comment]
Let me try to pick this up, Zak

**Comment by azaky** [comment]
Thanks! Go ahead, looking forward to your PR!

**Comment by azaky** [comment]
closed by #12
