### ISSUE TITLE
Article search autocomplete

### ISSUE THREAD

**Issue by azaky** [azaky/wikigame#5]
Currently, the user has to type the full article name in the input box. It's nice to have a search autocomplete.

To give you an idea, this is the built-in search autocomplete in Wikipedia:

![image](https://user-images.githubusercontent.com/5902356/95673516-48a96c80-0bd3-11eb-86dd-45deeb0c2053.png)

If one can reuse that, that's good. But creating for scratch is fine as well.

This is an API that you can use: https://en.wikipedia.org/w/api.php?action=opensearch&format=json&formatversion=2&search=book&namespace=0&limit=10

**Comment by muzavan** [comment]
Do we want to call wiki API directly or create a proxy in the wikigame server before call wiki API?

Wondering if we need additional process before calling Wiki API

(havent read the API though :p)

**Comment by azaky** [comment]
I think using the existing wiki API is fine, as this is only for the autocomplete.

FYI, article validation on server side is already implemented here b26fbf197fb81ac6d10ce0ee505a2e1bd57e9012, so inputting values like "usa" will get automatically transformed to "United_States".

**Comment by muzavan** [comment]
Okay then, let me pick this up 🙏

**Comment by azaky** [comment]
Thanks! Go ahead, looking forward to your PR!
